### ISSUE TITLE
Unable to set minimum exposure on ZWO camera

### ISSUE THREAD

**Issue by aaronwmorris** [indilib/pyindi-client#3]
**Describe the bug**
I am not sure if this is a python, ZWO, Indi, C, or ARM bug.  The minimum exposure for the ASI290MM is 0.000032 but if that exposure is set, the camera returns an error.  This was working in Indi 1.8.9.

I am able to set the minimum exposure in Ekos and indi_setprop, but not with pyindi-client

**To Reproduce**
Exact steps to reproduce the behavior.
1. Set ASI290MM minimum exposure to 0.000032 with pyindi-client

**Desktop (please complete the following information):**
 - OS:  Raspbian GNU/Linux 10 (buster)
 - Raspberry Pi 3
 - Version: 1.9.1
 - Python 3.7.3
 - pyindi-client  (git: 68803a1c51fb5aa271302a748e012cf0cee309b2)
 - Tested camera:  ASI290MM
 

**Log Files**
```
new Message 2021-08-20T15:41:02: [ERROR] Requested exposure value (3.2e-05) seconds out of bounds [3.2e-05,2000].
```

```
'CCD_EXPOSURE': {
  'CCD_EXPOSURE_VALUE': 
    {'current': 0.0,
     'format': '%5.2f',
     'max': 2000.0,
     'min': 3.2e-05,
     'step': 1.0}
},
```

**Comment by GoateePFE** [comment]
_swig/python detected a memory leak of type 'INDI::BaseDevice::Properties *', no destructor found._ 

I encountered this similar issue on my Raspberry Pi4b running Astroberry/Ekos/Kstars with the QHY268C camera. I could not set an exposure value less than 1 second for bias frames. See the details in this issue:

[](https://github.com/rkaczorek/astroberry-server/issues/181
)

How do I use indi_setprop with Ekos instead of pyindi-client?

First time posting here. Please excuse the lack of version info. I'm new to Pi. If you tell me how to get the info you need I can get it. Thanks.

**Comment by aaronwmorris** [comment]
I worked around this issue by adding a very small value (0.0000001) to the minimum exposure.  Closing this issue for now.
